public class FloatingPointClass {
	public static void myMethod()
    {
        //***DOUBLE DATATYPE***
        //Declaring a variable
        double d;
        //Assigning a value to variable
        d=25.234;
        //Declaring and Assigning a value to a variable together
        double d1=25.234;
        //integer a=25.234;
        //System.debug(a); // ILLEGAL ASSIGNMENT 
        
        //***DECIMAL DATATYPE***
        //Declaring a variable
        decimal dc1;
        //Assigning a value to variable
        dc1=593.45;
        //Declaring and Assigning a value to a variable together
        decimal dc2=593.45;
    }
}