public class IntegerClass {
	public static void myMethod()
    {
        //***INTEGER DATATYPE***
        //Declaring a variable
        integer a;
        //Assigning a value to variable
        a=50;
        //Declaring and Assigning a value to a variable together
        integer a1=50;
        
		//***LONG DATATYPE***
		//Declaring a variable
        long l1;
        //Assigning a value to variable
        l1=5000;
        //Declaring and Assigning a value to a variable together
        long l2=5000;
        
        //long l3=2147483648; // will give compile error
        //Consider it as an integer by default
        
        long l4=2147483641l;
        
        long l5=2147483641L;
    }
}